version: "3.9"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      - mynet

    environment:
      POSTGRES_DB: "paymentsdb"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "password123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - .:/var/lib/postgresql/data
  payment:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge