version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "paymentsdb"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "password123"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"